import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import { Box } from "@mui/material";
import Header from "@/components/layout-components/header/header";
import LanguageSelect from "@/components/LanguageSelect";
import Providers from "@/components/layout-components/Providers";
import "./globals.css";
import Head from "next/head";

const poppins = Poppins({subsets:['latin'], weight:['400', '700']})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
      <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-o+Hv6Wv9tQoAsUpo+2ybqKXXUvyTMF9efw3Cqmq5pqo="
          crossOrigin=""
        />
      </Head>
      <body className={poppins.className}>
        <Providers>
          <Box style={{ padding: "0.3rem 9rem", display: "flex", justifyContent: "flex-end", backgroundColor: '#f7f8f8', fontSize: '12px'}}>
            <LanguageSelect/>
          </Box>
          <Header/>
          <div className="">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
